### ISSUE TITLE
Please made piratebay provider for quasar

### ISSUE THREAD

**Issue by override187** [mancuniancol/repository.providers.quasar#1] opened 2016-02-01 20:34 UTC

**Comment by mancuniancol** [comment] 2016-02-01 22:36
The problem is not stable url address to work.

**Comment by override187** [comment] 2016-02-01 23:41
Yes i know that, but it isnt hard to change it manualy in settings and tpb is still best torrent site.

**Comment by mancuniancol** [comment] 2016-02-02 07:36
OK, I will work in it

**Comment by override187** [comment] 2016-02-02 09:34
OK, thank you for your support.

**Comment by mancuniancol** [comment] 2016-02-02 12:15
I've tried, but again, it is problem with ssl certificate and the simple python library couldn't open the piratebay url.
`File "C:\Users\mancuniancol\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 447, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error`

**Comment by mancuniancol** [comment] 2016-02-02 12:16
It is an old issue, that I don't know how to bypass without using pre-compilated libraries :(

**Comment by override187** [comment] 2016-02-02 17:15
Oke, thx for trying. Is this some problem with quasar since pulsar version works?

**Comment by mancuniancol** [comment] 2016-02-02 17:30
I get the same error.  Is it working for you?

**Comment by override187** [comment] 2016-02-02 17:42
Pulsar version works for me.

**Comment by mancuniancol** [comment] 2016-02-03 00:40
Which version do you have? I could just make the changes to be used by Quasar.

**Comment by override187** [comment] 2016-02-03 08:47
I was using latest version available in pulsar unofficial Repo.

**Comment by mancuniancol** [comment] 2016-02-03 09:09
I need the specific version. You can get it in the information of the script.

**Comment by mancuniancol** [comment] 2016-02-03 09:11
Because, it doesn't work in my side. Then, I want to get your version with the url that you are using to create the Quasar version.

**Comment by override187** [comment] 2016-02-03 12:02
Ver. 3.0.3, URL: thepiratebay.rs

**Comment by mancuniancol** [comment] 2016-02-03 12:06
I didn't know that url. All the problem is between https and http.  Your url is http.  Then, the python urllib can read that website without problem. I will release the provider in couple hours.  Thank you.

**Comment by mancuniancol** [comment] 2016-02-03 13:58
Ok, it is done.  Thank you again for the tip.  You can download it from here:
https://github.com/mancuniancol/script.quasar.thepiratebay-mc/archive/v1.0.0.zip

I will send it to the repo tonight.
I remind you that it only works with http url.  if you use https, it will give error.

I will close this issue.

**Closed by mancuniancol** 2016-02-03 13:58 UTC
